# Importing requried libraries

from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.core.mail import send_mail,EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.utils.encoding import force_bytes,force_str
import numpy as np
import authentication
from SE import settings
from . tokens import generate_token
from authentication.models import Contact
from datetime import datetime
import re
special_chars = ['!','#','?','$','&']
# Create your views here.

# View for home page which consist the url for index.html file which is the hoe page
def home(request):
    return render(request,'index.html')


# View for contact us page, where user can enter their details for get some contact information and for give some feedback
def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        desc = request.POST.get("desc")
        contact = Contact(name=name,email=email,phone=phone,desc=desc,date = datetime.today())
        contact.save()
        messages.success(request,"Your message has been sent !!")

    # return HttpResponse("Hello there, this is contact")
    return render(request,"contact.html")

# info about the developers 
def about(request):
    # return HttpResponse("Hello there, this is about us")
    return render(request,"about.html")
# view for signup module
def signup(request):

    
    # invoking user request, while user will enter details in sign up
    if(request.method == "POST"):
        username = request.POST['username']
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']
        pin = request.POST['pin']
        phone = request.POST['phone']
        
        # checking if username already exists
        if User.objects.filter(username=username):
            messages.error(request,"User_name already exist Please try some otther username")
            return redirect('home')

        # cheking if email already exist if exists then it will show an error.
        if User.objects.filter(email=email):
            messages.error(request,"Email already exist")
            return redirect('home')
        
        # username should be of length less tha 10
        if len(username) > 10:
            messages.error(request,"User name must be less than 10 characters")
            return redirect('home')
        
        # unique pin generated by user should be of length 6
        if( len(pin) != 6):
            messages.error(request,"Pin must be of length 6")
            return redirect('home')

        # password should contain exactly 1 special character 
        for i in pass1:
            if(i in special_chars):
                t1 = pass1.count(i)
                if(t1 != 1):
                    messages.error(request,"password should contain at least one special character among {'!','#','?','$','&'}")
                    return redirect('home')

                
        # length of password should be in range of [8,13]
        if( len(pass1)<8 or len(pass1)>13):
            messages.error(request,"Pin must be of length between 8 to 13")
            return redirect('home')
        
        # password should match with confirm password
        if pass1 != pass2:
            messages.error(request,"Passsword didn't match")
            return redirect('home')

        # username should be alpha numeric
        if not username.isalnum():
            messages.error(request,"Username must be alpha numberic")
            return redirect('home')
     
        # password should contain at least one upper case and one lower case letter.
        if(len(re.findall(r'[A-Z]',pass1))<1):
            messages.error(request,"Passwors should contain atleast one upper case")
            return redirect('home')
        
        if(len(re.findall(r'[a-z]',pass1))<1):
            messages.error(request,"Passwors should contain atleast one upper case")
            return redirect('home')

        
        # creating object for user
        myuser = User.objects.create_user(username,email,pass1)
        myuser.first_name = fname
        myuser.last_name = lname
        myuser.pin = pin
        myuser.is_active = False
        
        # saving the user
        myuser.save()

        # succes message for user if he/she get verified successfully
        messages.success(request,'Hello there, Your account has been succcesfully created. We have sent you an confirmation email, please confirm your email in order to activate your account.')

        # Welcome email : it will sent the welcome email to user after registration and a link will be shred to user for verify the accout.
        subject = 'Welcome to '
        message = f"Hello {myuser.first_name} !!\n\tWelcome, Thanks for visiting our website. \nWe have also sent you a confirmation email, please confirm your email in order to activate your account. \n\n Thanking you\nSecure SignUp"
        from_email = settings.EMAIL_HOST_USER
        to_list = [myuser.email]
        send_mail(subject,message,from_email,to_list,fail_silently=True)

        
        # Email for verification link
        current_site = get_current_site(request)
        email_subject = 'Confirm your Email at '
        message2 = render_to_string('email_confirmation.html',
            {'name':myuser.first_name,'domain':current_site.domain,'uid': urlsafe_base64_encode(force_bytes(myuser.pk)),
            'token': generate_token.make_token(myuser)}) 

               
        email = EmailMessage(email_subject,message2,settings.EMAIL_HOST_USER,[myuser.email],)
        email.fail_silently = True
        email.send()

        return redirect('Login')

    return render(request,'signup.html')


def activate(request,uidb64,token):

    # method for activating the account of the user after he/she click on the activation link.
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except(TypeError,ValueError,OverflowError,User.DoesNotExist):
        myuser = None

    if(myuser is not None and generate_token.check_token(myuser,token)):
        myuser.is_active = True
        myuser.save()
        login(request,myuser)
        return redirect('home')
    else:
        return redirect(request,'activation_failed.html')


def Login(request):

    # Login module for login the user 
    
    #invocking the user credentials entered by user
    if(request.method == "POST"):
        username = request.POST['username']
        pass1 = request.POST['pass1']
        pin = request.POST['pin']
        user = authenticate(username=username,password=pass1)
        # authenticating user based on username password and pin
        if(user is not None):
            login(request,user)
            fname = user.first_name
            return render(request,'index.html',{'fname':fname})
        
        else:
            messages.error(request,'Your are breaking my heart, you\'re not using the same credentials')
            return redirect('home')

    return render(request,'Login.html')

def signout(request):
    # signout module 
    
    # user will be signed out when he/she will click on it.
    logout(request)
    messages.success(request,"You've logged out succesfully, Hope we'll meet again")
    return redirect('home')
